### ISSUE TITLE
Fix Broken Crystals version

### ISSUE THREAD

**Issue by rielas** [NeuraLegion/example-actions#7]
The main goal here: to move from "Juice Shop" as a target for repeater to our brand "Broken Crystals".

But right now it causes different errors like this [one](https://github.com/NeuraLegion/example-actions/runs/3201288742?check_suite_focus=true).

We need to make [brokencrystals](https://github.com/NeuraLegion/example-actions/tree/brokencrystals) branch working.

**Comment by dinkopehar** [comment]
I managed to start scan within the `docker-compose`. From my perspective, since nexploit-cli references target by the `docker-compose` service name (http://brokencrystals.local), it should only work within the container. I will add pooling and stopping of scan at Monday and provide additional findings at here.

**Comment by dinkopehar** [comment]
I misunderstood the **brokencrystals.local** overall. It's used in repeater, not in docker-compose (_They belong to same context at first look_).
I modified `docker-compose.yml` and `run-ci.yml` file in a small way and it's now similar to `crawler` branch we have for juiceshop. I think that `container_name` or proxy service overall caused problems with "Unauthorized Access".

**Comment by dinkopehar** [comment]
Example of run from last Actions - https://nexploit.app/scans/7aNB5krWeukoMMRkfjjWD2 

So from the beginning, these were the problems from my perspective:
- name of proxy container was changed by `container_name`
- it had wrong port exposed (exposed 8000 to 3000, should expose anyport:80, maybe not even any since nexploit-cli receives http://brokencrystals.local as target)
- There were some containers missing from brokencrystals, such as keycloak
